apiVersion: v1
kind: Pod
metadata:
  name: privileged
spec:
  securityContext:
    seccompProfile:
      type: Unconfined
    appArmorProfile:
      type: Unconfined
  containers:
  - name: app
    image: paraddise/ubuntu
    securityContext:
      seccompProfile:
        type: Unconfined
      appArmorProfile:
        type: Unconfined
      privileged: true
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]