apiVersion: v1
kind: Pod
metadata:
  name: host-network
spec:
  hostNetwork: true
  containers:
  - name: app
    image: paraddise/ubuntu
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]